language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies copied this from like many github toolboxes out there
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - pip install .
  - pip install -r requirements.txt
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib theano  pandas pytest h5py
  - pip install skdata
  - source activate test-environment
  - python setup.py install

# command to run tests
script: 
  - coverage run nosetests

before_install:
  pip install codecov
after_success:
  codecov

