sudo: required
language: python

python:
  - "2.7"

# command to install dependencies copied this from like many github toolboxes out there
before_install:
  - pip install -U pip  
  - pip install -r requirements.txt   
  - pip install -U travis-sphinx   
  - pip install -U codecov    
  - pip install -U python-coveralls  

# Install packages
install:  
  - python setup.py install

# command to run tests
script: 
  - coverage run ./setup.py test

after_success:
  - codecov
  - coveralls