sudo: required
language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies copied this from like many github toolboxes out there
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib theano  
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - pip install codecov  
# Install packages
install:
  - pip install -r requirements.txt    
  - python setup.py install

# command to run tests
script: 
  - coverage 

after_success:
  codecov

