sudo: required
language: python

python:
  - "2.7"

before_install:
  - pip install pip  
  - pip install -r requirements.txt   
  - pip install travis-sphinx   
  - pip install codecov    
  - pip install pytest

install:  
  - python setup.py install

script: 
  - coverage run ./setup.py test

after_success:
  - codecov
